language: ruby
rvm:
- 2.6.5
env:
  global:
  - CC_TEST_REPORTER_ID=6ff37add0aecefe2ddea29e8ebbb74798071c5c2fcf9cf90e27bdb89196896bb
services:
- postgresql
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
install:
- bundle install
- nvm install node
- node -v
- npm i -g yarn
- yarn
script:
- bundle exec rails webpacker:compile
- bundle exec rspec
- bundle exec rubocop
branches:
  only:
  - master
after_script:
- "./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  skip_cleanup: true
  app: wepick
  on:
    repo: jasylwong/wepick
  run:
  - bundle exec rails db:migrate
  - bundle exec rails db:seed
  api_key:
    secure: zQiLzGacubjUrp38oC0pXFf5eYAvi6qVDbSPQ3F75FBRnFoBwxtpbn5xuGGRRhZfzEkYupCwML17nmbfGKPjMSGa+tcqLjsFx+oc2kGLALxXK+xY6eN/qKw9UvdfZYDTVQFOBhcD1DTG/cwKv4xX+EIj+fDeS9N/KiKqQNmARkiZ73jaPeRjmpayB5epjKbxgQa8VBiq/hJDLh/9YKaWLnYNwsIdjhFBZsvZDqZUzThc/V9jCRnfyCHnkqBTtT9iZLfS8/BIbg4RdCeP9kM4sCeuKz7Nhc4hHEIYmwOZnV/Vk0d+efkNnHDpcjZaJ/lLZ+mRs5Hai3d0wi5ePBJSZ7waU1x3VuvghkHdqdB4+4I2kFeSzeCC/hPkDJW7Co3HbH+KC+VsDIjIooROeWdFP533MSm18/Wipz1xjEruy9gXrb06aHzSpud+4y27Y09IVtLMjHAbdNCPkEhd4iFi/WAKT+Km5G+JD4YdY7MrjyM5NJdEoIFo+27KP0DEa9wqOdYaUHjGU83mrjtYjxj/XOdKY9eHcQLzX05N+NH0FFvzXodGFuEMVTAwmACoJtcei5ghwDw5b1iT16uXFdYoGQH5lQs3z81WbRhlW/lM+sfWP/LVQFb+rnjJwiYawVeF852k/TOKVnIucKCfmVP0v3atIonI5X6XEYPJLBb50Ek=
