language: ruby
rvm:
- 2.6.5

env:
- DB=postgresql

services:
- postgresql

before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate

script:
- bundle
- bundle exec rspec
- bundle exec rubocop

after_script: